List<String> categories = [
  "Advertising & Marketing", // 0
  "Administration & Office", // 1
  "Art, Fashion & Design", // 2
  "Education", // 3
  "Healthcare", // 4
  "Installation, Maintenance & Repair", //5
  "Restaurant & Hospitality", // 6
  "Sales & Retail", // 7
  "Others", //8
];

List<Map> jobCategories = [
  {
    "category": "Advertising & Marketing",
    "workPosition": [
      "Sales representative",
      "Sales manager",
      "Salesperson",
      "Blogger",
      "Content editor",
      "Promoter",
    ],
    "responsibilities": [
      "- Generating, researching, and pitching ideas for posts.",
      "- Writing, editing, publishing, and promoting content.",
      "- Promoting new posts using advertisements, emails, social media, and other methods to alert and attract new readers.",
      "- Advocating and educating others about interests, products, or services.",
      "- Maximizing site traffic by utilizing Search Engine Optimization keywords.",
      "- Inviting other bloggers, experts, or other notable guests to contribute content to the webpage.",
      "- Monitoring responses to posts via the website, social media, or other platforms to better understand the audience.",
      "- Staying current on industry trends for possible opportunities to attract new readers or create stronger, more engaging content.",
      "- Supervise a team of writers and coordinate with freelance contributors.",
      "- Proofread and edit spelling, grammar and syntax.",
      "- Ensure that content meets the company or client's needs, and follows our in-house style guide.",
      "- Organize, modify and update existing content.",
      "- Verify content and information.",
      "- Work with the graphic design team to ensure a user-friendly experience.",
      "- Collaborate with co-workers and come up with fresh, creative content ideas, keeping our audience in mind.",
      "- Manage a busy workload according to deadline.",
      "- Analyze data and analytics, and seek to increase reader engagement and retention.",
      "- Knowledge of SEO and industry best practices.",
      "- Represent the organization at launches, meetings, and press events.",
      "- Setting up and maintaining a demonstration area, such as a table, stand, or booth at various events.",
      "- Keeping the demonstration area tidy and well stocked with products, samples, and/or literature.",
      "- Demonstrating the features of a product or service to potential customers.",
      "- Employing interactive materials such as videos, charts, or slideshows to share information about a product or service, when necessary.",
      "- Answering any questions potential customers might have about a product or service.",
      "- Recording transactions and stock levels.",
      "- Processing customers’ payments.",
      "- Generating reports that outline customers’ interest levels, questions asked, number of products/samples/literature sold and/or distributed at various events.",
      "- Staying up to date with product or service features.",
    ],
    "requirements": [
      "- Bachelor’s degree in English, Communications, Marketing, or related field.",
      "- Writing experience or familiarity with certain interests or a specific field.",
      "- Exceptional writing, research, and communication skills.",
      "- Creativity and adaptability.",
      "- Strong understanding of the target audience and industry trends.",
      "- Proficiency with computers, especially content management software, social media platforms, MS Office, and SEO keywords, basic understanding of HTML",
      "- Ability to sit and type for extended periods.",
      "- Bachelor's Degree in Journalism, English or related field.",
      "- Excellent command of the English language.",
      "- Writing, copy editing, and proofreading experience.",
      "- Good communication and interpersonal skills.",
      "- Highly organized and detail oriented.",
      "- Proficient in desktop publishing software.",
      "- Proficient in Microsoft Office and Social Media platforms.",
      "- High school diploma.",
      "- Bachelor’s degree in marketing, or a related field, preferred.",
      "- Proven working experience as a Promoter.",
      "- Excellent communication, presentation, and leadership skills.",
      "- Proven track record of successful promotions.",
      "- Customer-oriented approach.",
      "- Outgoing and friendly personality.",
      "- Professional appearance.",
      "- Proficient in Microsoft Office Suite.",
    ],
  },
  {
    "category": "Administration & Office",
    "workPosition": [
      "Administrative officer",
      "Front Desk Clerk",
      "Client Services Coordinator",
      "Librarian",
      "Office Assistant",
      "File Clerk",
    ],
    "responsibilities": [
      "- Welcome clients and offer them refreshments.",
      "- Transcribe, record, fax and file documents.",
      "- Maintain filing, database systems, and inventories.",
      "- Operate office equipment such as photocopiers and fax machines.",
      "- Communicate with clients and employees, and respond to any queries or complaints.",
      "- Sort and forward incoming mail and emails, and prepare and send outgoing mail.",
      "- Book and prepare meeting rooms and ensure that refreshments are made available.",
      "- Book flights and accommodation as required.",
      "- Coordinate activities and disseminate information to office staff.",
      "- Greet guests and provide them with superb customer service.",
      "- Ensure the front desk is neat, presentable, and equipped with all the necessary supplies such as pens, forms, and paper.",
      "- Answer all client questions and incoming calls.",
      "- Redirect phone calls to the appropriate department and take down messages.",
      "- Accept all letters and packages, and distribute them to their appropriate departments.",
      "- Monitor, organize and forward emails.",
      "- Track and order office equipment and supplies.",
      "- Maintain records and files.",
      "- Oversee the office budget.",
      "- Record, edit and distribute minutes of council meetings.",
      "- Communicate effectively with management, government officials and staff.",
      "- Act as a liaison between the City Council and the public.",
      "- Draft meeting agendas and bylaws.",
      "- Record data and ensure that documents are stored, filed and maintained correctly.",
      "- Utilize computer databases and software.",
      "- Prepare and maintain official reports, legal documents, financial records, and reference material.",
      "- Coordinate municipal elections.",
      "- Transcribe, type and proofread documents.",
      "- Distribute public correspondence and ensure that municipal records are accessible to the public.",
    ],
    "requirements": [
      "- High school diploma or relevant qualification.",
      "- A minimum of 2 years’ proven experience in a similar role.",
      "- Good understanding of office administration and basic bookkeeping practices.",
      "- Superb written and verbal communication skills.",
      "- Excellent organizational and multi-tasking abilities.",
      "- Strong knowledge of MS Office programs.",
      "- High School diploma with relevant experience.",
      "- Certificate in Office Administration or Associate's Degree in Office Management may be required.",
      "- Strong Computer skills and working knowledge of Microsoft Office.",
      "- Time management and organizational skills.",
      "- Attention to detail.",
      "- Personable demeanor.",
      "- Ability to type 45 - 60 WPM (words per minute).",
      "- Bachelor's Degree in Business Administration, Public Administration or related field.",
      "- Previous experience preferred.",
      "- Computer skills and knowledge of software applications.",
      "- Excellent verbal and written communication skills.",
      "- Strong interpersonal skills.",
      "- Time management and organizational skills.",
      "- Compliance with all federal, state and local laws and regulations.",
    ]
  },
  {
    "category": "Art, Fashion & Design",
    "workPosition": [
      "Fashion designer",
      "Designer",
      "Dress designer",
      "Interior designer",
      "Furniture designer",
      "Graphic designer",
      "Artist",
      "Painter",
      "Sculptor",
      "Architect",
    ],
    "responsibilities": [
      "- Planning lessons on art and art history in accordance with students' learning objectives.",
      "- Preparing the classroom by gathering and setting up equipment.",
      "- Developing students' drawing, coloring, and painting techniques.",
      "- Providing instruction on the use of media such as graphite and charcoal pencils, as well as oil, acrylic, and watercolor paint.",
      "- Teaching students about art history.",
      "- Assigning and grading projects and examinations.",
      "- Recording and reporting on students' progress.",
      "- Ensuring that the classroom is clean after each lesson.",
      "- Monitoring inventory and sourcing art supplies, as needed.",
      "- Attending faculty and parent-teacher meetings.",
      "- Meeting with clients and determining their needs and requirements.",
      "- Managing design projects from concept development through to completion.",
      "- Developing and presenting project proposals.",
      "- Adjusting designs and plans to meet the client's needs.",
      "- Preparing drawings, blueprints, specifications and construction documents.",
      "- Conducting research and compiling reports on feasibility and environmental impact.",
      "- Complying with safety standards and local planning regulations.",
      "- Determining and adhering to budgets and timelines.",
      "- Managing project teams and collaborating with other construction professionals.",
      "- Meeting with clients to ascertain the intended functions and appearance of each space.",
      "- Anticipating and informing clients of additional features which may be of use to them.",
      "- Giving careful consideration to the placement of water and electrical systems to ensure safety.",
      "- Creating a plan which details the layout and appearance of all installations and loose furniture.",
      "- Suggesting appropriate materials and finishes.",
      "- Assisting clients to select and supervise the work of independent contractors, so that their duties are conducted in accordance with clients' visions.",
      "- Informing clients about appropriate care for their kitchens.",
      "- Keeping a record of hours and activities completed to ensure that clients are billed accurately.",
      "- Observing prescribed building and safety regulations.",
      "- Outline client design objectives.",
      "- Conceptualize and sketch design plans.",
      "- Determine cost of completion and project requirements in the budgeting phase.",
      "- Set a timeline for the completion of an interior design project.",
      "- Source materials and products included in plans.",
      "- Create 'mood boards' to sample your design vision.",
      "- Utilize computer applications in the design process.",
      "- Inspect design after completion to determine whether client goals have been met.",
    ],
    "requirements": [
      "- Bachelor's degree in Fine Arts with teaching qualification, or equivalent.",
      "- Prior experience as an Art Teacher.",
      "- Demonstrated excellence in a variety of art techniques.",
      "- Excellent verbal and written communication skills.",
      "- Capacity to supervise group work.",
      "- Outstanding planning and problem-solving skills.",
      "- Supportive, flexible disposition.",
      "- Available to work during evenings, on occasion.",
      "- Degree in Architecture or a related field.",
      "- Previous experience as an Architect preferred.",
      "- Excellent technical drawing skills.",
      "- Strong communication and project management skills.",
      "- Knowledge of Microsoft Office and software programs such as AutoCAD, Revit, Adobe Creative Suite, Newforma, etc.",
      "- Good interpersonal and presentation skills.",
      "- Knowledge of building codes and regulatory standards.",
      "- Strong creative and visualization skills.",
      "- High school diploma.",
      "- Prior experience as a Kitchen Designer.",
      "- Familiarity with appropriate design and visualization tools.",
      "- Catalog of completed blueprints, plus completed kitchens.",
      "- In-depth knowledge of and strict adherence to the area's building codes.",
      "- Top-notch communication and customer service skills.",
      "- Active listening skills and attention to detail.",
      "- Excellent organizational and time management skills.",
      "- Respect for differing opinions, styles, and financial situations.",
      "- Bachelor's degree in Interior Design or related field.",
      "- Portfolio of design work.",
      "- Project management experience.",
      "- Experience with computational design.",
      "- Highly creative, imaginative and artistic.",
      "- Excellent communication skills, especially in regard to communicating an artistic vision.",
      "- Proficiency in AutoCAD, Illustrator, SketchUp or similar design software.",
    ],
  },
  {
    "category": "Education",
    "workPosition": [
      "Driver Education Teacher",
      "Day Care Assistant",
      "Day Care Center Teacher",
      "Coach",
      "Child Care Assistant",
      "Child Care Center Teacher",
    ],
    "responsibilities": [
      "- Planning lessons on art and art history in accordance with students' learning objectives.",
      "- Preparing the classroom by gathering and setting up equipment.",
      "- Developing students' drawing, coloring, and painting techniques.",
      "- Providing instruction on the use of media such as graphite and charcoal pencils, as well as oil, acrylic, and watercolor paint.",
      "- Teaching students about art history.",
      "- Assigning and grading projects and examinations.",
      "- Recording and reporting on students' progress.",
      "- Ensuring that the classroom is clean after each lesson.",
      "- Monitoring inventory and sourcing art supplies, as needed.",
      "- Attending faculty and parent-teacher meetings.",
      "- Planning and presenting lessons to facilitate students' understanding and application of mathematical concepts.",
      "- Preparing and distributing learning material such as notes, assignments, and quizzes.",
      "- Sourcing the resources and supplies needed for lessons.",
      "- Ensuring that the classroom remains safe and conducive to learning.",
      "- Grading assignments and quizzes in a timely manner.",
      "- Invigilating quizzes and final examinations.",
      "- Documenting and reporting on students' progress.",
      "- Attending meetings with parents and staff.",
      "- Preparing and presenting lessons that facilitate students' cognitive, social, and emotional development.",
      "- Ensuring that you have sufficient classroom supplies at all times.",
      "- Creating a learning environment that is safe and nurturing.",
      "- Supervising children during lessons, meal time, and on the playground.",
      "- Assisting students to resolve conflict with others.",
      "- Monitoring and notifying caregivers of students' progress.",
      "- Notifying the Department Head and caregivers of accidents or other noteworthy incidents that occur while students are under your supervision.",
      "- Attending meetings with staff and caregivers, as required.",
      "- Accompanying students on field trips, as needed.",
    ],
    "requirements": [
      "- Bachelor's degree in Fine Arts with teaching qualification, or equivalent.",
      "- Prior experience as an Art Teacher.",
      "- Demonstrated excellence in a variety of art techniques.",
      "- Excellent verbal and written communication skills.",
      "- Capacity to supervise group work.",
      "- Outstanding planning and problem-solving skills.",
      "- Supportive, flexible disposition.",
      "- Available to work during evenings, on occasion.",
      "- Bachelor's degree in Education with a specialization in Mathematics, or equivalent.",
      "- Proven experience as a Math Teacher.",
      "- A thorough understanding of best practices in teaching.",
      "- Excellent verbal and written communication skills.",
      "- Organized, flexible disposition.",
      "- Outstanding interpersonal skills.",
      "- Bachelor's degree in Education, preferably with a focus on Early Childhood Development.",
      "- Clear criminal record.",
      "- Proven experience working with young children, ideally in a similar role.",
      "- Physically fit and able to stand for long periods.",
      "- Ability to lift up to 70 pounds independently.",
      "- Valid driver's license with own transport is advantageous.",
      "- Basic first aid training is preferable.",
      "- Excellent organizational and problem-solving skills.",
      "- Energetic, nurturing, and flexible disposition.",
      "- Ability to work during evenings and on weekends, as needed.",
    ],
  },
  {
    "category": "Healthcare",
    "workPosition": [
      "Dermatology Nurse",
      "Dialysis Nurse",
      "Home Health Nurse",
      "Carer",
      "Clinical Liaison",
      "ER Nurse",
    ],
    "responsibilities": [
      "- Being ready to respond and equipped to deal with a medical emergency.",
      "- Quickly assessing patient needs.",
      "- Treating critical injuries, allergic reactions and trauma.",
      "- Performing minor medical operations.",
      "- Cleaning wounds.",
      "- Drawing blood.",
      "- Maintaining emergency room care standards.",
      "- Assisting with insurance paperwork.",
      "- Ensuring the efficiency of the patient check-in process.",
      "- Displaying strong decision-making skills in emergency scenarios.",
      "- Implementing marketing plans to achieve sales goals.",
      "- Cultivating relationships with sources to generate repeat referrals.",
      "- Participating in facility's marketing education, ensuring knowledge of their resources and maintaining knowledge of competitor facilities.",
      "- Providing facility tours and conducting presentations for potential referral sources and patient families.",
      "- Attending seminars and conferences to promote facility.",
      "- Collaborating with facility personnel regarding referrals, evaluations and marketing activities.",
      "- Reviewing physicians' orders and patients' clinical needs, and gathering clinical information.",
      "- Conducting assessments to establish suitability of prospective admissions.",
      "- Communicating activities and concerns to supervisor.",
      "- Completing required paperwork, managing correspondence and maintaining data in CRM.",
      "- Liaising with familial and medical support structures to ascertain residents' care-related requirements.",
      "- Running errands to ensure that the site remains well-stocked.",
      "- Preparing adequate, nutritional meals and assisting with feeding upon request.",
      "- Performing routine, ad hoc household chores.",
      "- Assisting residents to maneuver safely.",
      "- Clearing spaces from potentially hazardous implements.",
      "- Installing assistive devices to prompt self-directed, less restrained functioning.",
      "- Supervising and assisting with treatment adherence.",
      "- Providing unwavering, appropriate emotional support.",
    ],
    "requirements": [
      "- American Heart Association Basic Life Support (BLS) certification.",
      "- Advanced Cardiac Life Support (ACLS) certification.",
      "- Certified Emergency Nurse (CEN) certification and Crisis Prevention and Intervention (CPI) certification advantageous.",
      "- Able to work under high pressure.",
      "- Attention to detail.",
      "- Good organizational skills.",
      "- Excellent written and verbal communication.",
      "- Bachelor’s Degree in nursing or related field.",
      "- 2+ years work experience in healthcare-related marketing.",
      "- Active clinical license.",
      "- Proficient knowledge of Stark laws.",
      "- Proficient computer skills.",
      "- Valid driver’s license with up-to-date insurance.",
      "- Excellent communication skills, using diplomacy and discretion.",
      "- Professional demeanor.",
      "- Excellent organizational skills.",
      "- High school diploma.",
      "- Completion of a Home-Based Caring qualification.",
      "- Demonstrable experience as Carer or similar.",
      "- Driver's license.",
      "- Gentle and clear verbal communication skills.",
      "- Unobtrusive monitoring skills.",
      "- Earnestly compassionate, resourceful, and sensible.",
      "- Physically mobile with good arm strength.",
    ],
  },
  {
    "category": "Installation, Maintenance & Repair",
    "workPosition": [
      "Carpenters",
      "Electricians",
      "Plumbers",
      "Pipefitters",
      "Steamfitters",
      "Mechanics",
      "Installers"
    ],
    "responsibilities": [
      "- Preparing construction sites, materials, and tools.",
      "- Loading and unloading of materials, tools, and equipment.",
      "- Removing debris, garbage, and dangerous materials from sites.",
      "- Assembling and breaking down barricades, temporary structures, and scaffolding.",
      "- Assisting contractors, e.g. electricians and painters, as required.",
      "- Assisting with transport and operation of heavy machinery and equipment.",
      "- Regulating traffic and erecting traffic signs.",
      "- Following all health and safety regulations.",
      "- Digging holes, tunnels, and shafts.",
      "- Mixing, pouring, and leveling concrete.",
      "- Inspecting the structure of roofs in order to determine the best course of action.",
      "- Providing clients with estimates on labor costs and materials required to fix or build a roof.",
      "- Measuring and cutting materials to ensure that they fit securely around vents, gutters, chimneys, and walls.",
      "- Smoothing out rough spots on roofs to prepare the surface for new shingles or waterproofing.",
      "- Replacing areas of clients’ roofs that are damaged or rotting.",
      "- Installing vapor barriers and insulation to create a more waterproof seal.",
      "- Safely setting up ladders, scaffolding and hoisting equipment as required.",
      "- Updating the supervisor on job progress and reporting any problems related to the job.",
      "- Safely transporting all required equipment and materials to job sites.",
      "- Create and maintain construction schedules.",
      "- Hire and manage staff.",
      "- Liaise with property owners and tenants.",
      "- Order materials as needed.",
      "- Ensure that projects remain within the allotted budget.",
      "- Ensure that safety protocols are followed.",
    ],
    "requirements": [
      "- No formal qualification is required, although a high school diploma may be preferred.",
      "- Similar work experience may be beneficial.",
      "- Licensure to work with hazardous materials may be required.",
      "- Willingness to undertake training if necessary.",
      "- Be mild-tempered and a team player.",
      "- Be healthy, strong, and fit.",
      "- High school diploma or GED.",
      "- Valid driver's license.",
      "- State roofer's license.",
      "- Proven roofing or general construction experience.",
      "- Working knowledge of different roofing systems.",
      "- Sound knowledge of business ordinances.",
      "- The ability to lift heavy materials and tools.",
      "- The ability to use powered hand tools.",
      "- Excellent communication skills.",
      "- Exceptional customer service skills.",
      "- Prior experience in a supervisory role.",
      "- Experience with construction.",
      "- Excellent project management skills.",
      "- Good interpersonal skills.",
      "- Excellent leadership skills.",
    ],
  },
  {
    "category": "Restaurant & Hospitality",
    "workPosition": [
      "Waiter",
      "Chef",
      "Baker",
      "Hostess",
      "Kitchen Staff",
      "Food Server",
      "Food Handler",
    ],
    "responsibilities": [
      "- Cleaning all dishes, work stations, cooking equipment, and food storage areas in accordance with food safety regulations.",
      "- Washing, chopping, shredding, and grating ingredients for subsequent use by the Chef.",
      "- Sweeping and mopping floors, as required.",
      "- Assisting with the unloading of deliveries.",
      "- Storing ingredients according to prescribed food safety regulations.",
      "- Assisting with the monitoring of inventory.",
      "- Reporting all damaged or faulty equipment to the Kitchen Manager.",
      "- Packaging customers' leftover food upon request.",
      "- Cleaning trash cans and disposing refuse on a regular basis.",
      "- Preparing various food items for customers in accordance with the instructions provided.",
      "- Appropriately packaging all food items for delivery.",
      "- Cleaning and disinfecting all food preparation tools, instruments, and equipment before and after each use.",
      "- Ensuring that all food surfaces, as well as refrigerators, ovens, freezers, and microwaves, are clean.",
      "- Promptly notifying the supervisor of any incidents or suspicions of food contamination.",
      "- Cleaning up all spills and leaks as and when they occur to avoid accidents.",
      "- Following proper food storage procedures to prevent spoilage.",
      "- Monitoring food supplies and informing the supervisor of low stock to ensure that the food preparation process isn’t disrupted or delayed due to insufficient ingredients.",
      "- Preparing food rotation labels and labeling all food items accordingly.",
      "- Ensuring that all food is of excellent quality and served in a timely manner.",
      "- Planning the menu, keeping in mind budget and availability of seasonal ingredients.",
      "- Overseeing all kitchen operations.",
      "- Coordinating kitchen staff, and assisting them as required.",
      "- Training staff to prepare and cook all the menu items.",
      "- Taking stock of ingredients and equipment, and placing orders to replenish stock.",
      "- Enforcing safety and sanitation standards in the kitchen.",
      "- Creating new recipes to keep the menu fresh.",
      "- Keeping up to date with industry trends.",
      "- Receiving feedback and making improvements where necessary.",
    ],
    "requirements": [
      "- High school diploma or equivalent.",
      "- Prior experience in a similar position.",
      "- Thorough knowledge of food safety procedures.",
      "- Excellent organizational, time management, and multitasking abilities.",
      "- Outstanding interpersonal skills.",
      "- Ability to lift up to 50 pounds.",
      "- Capacity to work in a fast-paced environment.",
      "- Ability to stand for extended periods.",
      "- Ability to work shifts, over weekends, and on public holidays, as needed.",
      "- High school diploma or GED.",
      "- A Food Handler's license.",
      "- Proven experience working in the foodservice industry.",
      "- Sound knowledge of food health and safety regulations.",
      "- The ability to follow proper food handling procedures.",
      "- The ability to stand for extended periods.",
      "- The ability to work as part of a team.",
      "- Excellent organizational, time management, and problem-solving skills.",
      "- Effective communication skills.",
      "- Culinary school degree/diploma.",
      "- Past experience as a working chef.",
      "- Advanced knowledge of the culinary arts.",
      "- Perfectionism in sanitation and quality control.",
      "- Portfolio of creative, unique dishes.",
      "- Expert multitasking ability.",
      "- Great leadership and interpersonal skills.",
      "- Ability to run stocktaking and place orders for resupply.",
      "- Exemplary work ethic in a high-pressure environment.",
      "- Passion and pride for delighting people with food.",
    ],
  },
  {
    "category": "Sales & Retail",
    "workPosition": [
      "Cashier",
      "Seller",
      "Merchant",
      "Distributor",
    ],
    "responsibilities": [
      "- Welcoming customers, answering their questions, helping them locate items, and providing advice or recommendations.",
      "- Operating scanners, scales, cash registers, and other electronics.",
      "- Balancing the cash register and generating reports for credit and debit sales.",
      "- Accepting payments, ensuring all prices and quantities are accurate and proving a receipt to every customer.",
      "- Processing refunds and exchanges, resolving complaints.",
      "- Bagging or wrapping purchases to ensure safe transport.",
      "- Following all store procedures regarding coupons, gift cards, or the purchase of specific items, such as alcohol or cigarettes.",
      "- Maintaining a clean workspace.",
      "- Planning and developing merchandising strategies.",
      "- Analyzing sales figures, market trends and customer behavior to determine product needs.",
      "- Stocking sales floor shelves and creating attractive product displays.",
      "- Determining the need for and implementing product promotions, price changes, mark downs, clear outs, etc.",
      "- Ensuring retail staff are well informed on product details and promotions.",
      "- Maintaining and tracking inventory.",
      "- Liaising between customer and company.",
      "- Forecasting sales and profits.",
      "- Managing budgets.",
      "- Research, select and purchase quality products and materials.",
      "- Build relationships with suppliers and negotiate with them for the best pricing.",
      "- Process requisitions and update management on status of orders.",
      "- Update inventory and ensure that stock levels are kept at appropriate levels.",
      "- Arrange transport of goods and track orders to ensure timely delivery.",
      "- Analyze market trends and apply this knowledge to make insightful buying decisions.",
      "- Coordinate with inventory team, management, and stockroom as required.",
      "- Assess quality of stock received and escalate any discrepancies to suppliers and management.",
      "- Ability to travel.",
    ],
    "requirements": [
      "- High School Diploma or equivalent.",
      "- Customer service or Cashier experience.",
      "- Ability to handle transactions accurately and responsibly.",
      "- High level of energy with strong customer service skills.",
      "- Basic math and computer skills.",
      "- Ability to stand, walk, lift heavy items, and work with other team members in a fast-paced environment to provide excellent service.",
      "- Attention to detail.",
      "- Helpful, courteous approach to resolving complaints.",
      "- High school diploma/GED required.",
      "- Previous experience in merchandising or retail preferred.",
      "- Degree in business, marketing, retail or related field may be preferred.",
      "- Strong organisational and decision making skills.",
      "- Excellent communication skills, both written and verbal.",
      "- Strong numerical and analytical skills.",
      "- Commercial awareness.",
      "- Valid driver's license.",
      "- Bachelor's Degree in relevant field.",
      "- Relevant experience preferred.",
      "- Excellent computer skills (Excel, Microsoft Word, PowerPoint).",
      "- Proficient in appropriate software.",
      "- Critical thinking and negotiation skills.",
      "- Strong communication skills, both written and verbal.",
      "- Occasional domestic and/or international travel.",
    ],
  },
  {
    "category": "Others",
    "workPosition": [
      "Veterinary receptionist",
      "Beekeeper",
      "Bog handler",
      "Florist",
    ],
    "responsibilities": [
      "- Conducting environmental site assessments.",
      "- Identifying wetland delineations, and coordinating threatened and endangered species management.",
      "- Conducting habitat evaluations, including presence-absence surveys.",
      "- Collecting specimens.",
      "- Managing storm water run-off, and monitoring erosion control.",
      "- Monitoring construction projects.",
      "- Processing, capturing and analyzing data.",
      "- Compiling technical reports and findings.",
      "- Planning and overseeing field work, and acting as in-field leader for junior staff and technicians.",
      "- Ensuring compliance with safety protocols and procedures.",
      "- Consulting with clients to discuss behavioral concerns and training needs.",
      "- Identifying additional behavioral concerns and communicating them to clients.",
      "- Developing suitable training plans for dogs and documenting their progress.",
      "- Teaching dogs to obey basic commands using various training techniques that are best suited to each dog’s personality and attributes.",
      "- Implementing appropriate training programs to address and resolve problem areas, including aggression, separation anxiety, hyperactivity, and biting.",
      "- Ensuring that the training areas are clean and tidy.",
      "- Teaching clients appropriate training methods to enforce and maintain behaviors and skills learned by their dogs during training sessions.",
      "- Contacting clients to schedule training appointments, verify bookings, and inquire into overdue payments.",
      "- Assembling beehives to desired specifications.",
      "- Inserting honeycombs and inducting wild swarms into prepared hives.",
      "- Forcing bees from a hive using a smoke pot to inspect the hive and retrieve honey.",
      "- Collecting honey and royal jelly.",
      "- Destroying excess queen bee cells to prevent the division of a colony.",
      "- Scraping out hive parasites and removing vermin.",
      "- Destroying diseased bee colonies.",
      "- Cultivating queen bees for sale to other Apiarists.",
      "- Arranging the sale of honey to local buyers.",
      "- Splitting colonies.",
    ],
    "requirements": [
      "- High school diploma or GED.",
      "- Certification through the Certification Council for Professional Dog Trainers (CCPDT) is advantageous.",
      "- Sound knowledge of dog training techniques as well as animal behavior and body language.",
      "- Proven experience working as a Dog Trainer.",
      "- Excellent problem-solving, organizational, and time management skills.",
      "- Strong dog handling skills.",
      "- Effective communication skills.",
      "- A love for dogs.",
      "- Patient and enthusiastic.",
      "- Master’s degree in natural resources, ecology, forestry, environmental science or related field.",
      "- 3+ years work experience in similar role.",
      "- USFSW scientific collection permits.",
      "- Proficient computer skills.",
      "- Proficient with GIS and GPS.",
      "- Knowledge of absence-presence surveys.",
      "- Outstanding communication skills, both verbal and written.",
      "- Ability to work outdoors in unpleasant climatic conditions.",
      "- Valid driver’s license.",
      "- Availability to travel.",
      "- Safety-minded.",
      "- High school diploma or GED.",
      "- Degree in Zoology or Animal Science preferred.",
      "- Proven work experience as a Beekeeper.",
      "- Excellent knowledge of plant and animal biology.",
      "- Ability to remain calm in stressful situations.",
      "- Basic woodworking skills.",
      "- Ability to lift heavy objects.",
      "- Ability to work flexible hours.",
      "- Ability to work unsupervised.",
      "- Ability to work outdoors in all weather conditions.",
    ],
  },
];
