List<String> categories = [
  "Advertising, Media & Marketing", // 0
  "Administration & Office", // 1
  "Art, Fashion & Design", // 2
  "Education", // 3
  "Healthcare", // 4
  "Construction, Installation & Repair", //5
  "Restaurant & Hospitality", // 6
  "Sales & Retail", // 7
  "Others", //8
];

List<Map> jobCategories = [
  {
    "category": "Advertising, Media & Marketing",
    "workPosition": [
      "Sales representative",
      "Sales manager",
      "Salesperson",
      "Blogger",
      "Content editor",
      "Promoter",
      "Film Editor",
      "Journalist",
      "Marketing Analyst",
      "Video Editor",
      "YouTuber",
      "Videographer",
      "Model",
      "Executive Producer",
      "Film Director",
      "Digital Producer",
      "Creative Writer",
      "Advertising Manager",
    ],
    "responsibilities": [
      "- Generating, researching, and pitching ideas for posts.",
      "- Writing, editing, publishing, and promoting content.",
      "- Promoting new posts using advertisements, emails, social media, and other methods to alert and attract new readers.",
      "- Advocating and educating others about interests, products, or services.",
      "- Maximizing site traffic by utilizing Search Engine Optimization keywords.",
      "- Inviting other bloggers, experts, or other notable guests to contribute content to the webpage.",
      "- Monitoring responses to posts via the website, social media, or other platforms to better understand the audience.",
      "- Staying current on industry trends for possible opportunities to attract new readers or create stronger, more engaging content.",
      "- Supervise a team of writers and coordinate with freelance contributors.",
      "- Proofread and edit spelling, grammar and syntax.",
      "- Ensure that content meets the company or client's needs, and follows our in-house style guide.",
      "- Organize, modify and update existing content.",
      "- Verify content and information.",
      "- Work with the graphic design team to ensure a user-friendly experience.",
      "- Collaborate with co-workers and come up with fresh, creative content ideas, keeping our audience in mind.",
      "- Manage a busy workload according to deadline.",
      "- Analyze data and analytics, and seek to increase reader engagement and retention.",
      "- Knowledge of SEO and industry best practices.",
      "- Represent the organization at launches, meetings, and press events.",
      "- Setting up and maintaining a demonstration area, such as a table, stand, or booth at various events.",
      "- Keeping the demonstration area tidy and well stocked with products, samples, and/or literature.",
      "- Demonstrating the features of a product or service to potential customers.",
      "- Employing interactive materials such as videos, charts, or slideshows to share information about a product or service, when necessary.",
      "- Answering any questions potential customers might have about a product or service.",
      "- Recording transactions and stock levels.",
      "- Processing customers’ payments.",
      "- Generating reports that outline customers’ interest levels, questions asked, number of products/samples/literature sold and/or distributed at various events.",
      "- Staying up to date with product or service features.",
      "- Work with the brand team to produce new ideas for company branding, promotional campaigns, and marketing communications.",
      "- Evaluate trends, assess new data and keep up-to-date with the latest marketing techniques.",
      "- Assist clients in resolving issues by responding to questions in a timely and professional manner.",
      "- Create and implement tailored marketing plans based on individual client requirements.",
      "- Direct brainstorming meetings and creative sessions.",
      "- Shape brand standards and create procedures to ensure all products are brand appropriate.",
      "- Supervise the department's daily workflow, assign project workload, and monitor deadlines and budgets.",
      "- Develop exceptional and well-crafted copy that meet clients’ requirements.",
      "- Conducting research before and during the writing process.",
      "- Preparing material for assignments, which includes planning, outline, and synopsis.",
      "- Conducting thorough fact-checks before submitting any work.",
      "- Ensuring the logical flow of all writing produced.",
      "- Attending feedback sessions and making revisions suggested by the client, publisher or editors.",
      "- Attending training sessions and workshops as required.",
      "- Following the directions of photographers and posing for photoshoots accordingly.",
      "- Participating in advertisements and television commercials to promote various products and services.",
      "- Participating in runway shows by modeling designers’ clothing, accessories, footwear, and jewelry.",
      "- Participating in trade shows and conventions to advertise business products.",
      "- Maintaining an updated portfolio of work.",
      "- Collaborating with hair and clothing stylists as well as makeup artists to create specific looks.",
      "- Following suitable health and fitness regimens to maintain a well-defined physical appearance in accordance with industry standards.",
      "- Conducting research on designers’ fashionwear as well as other products that are to be modeled and promoted.",
    ],
    "requirements": [
      "- Bachelor’s degree in English, Communications, Marketing, or related field.",
      "- Writing experience or familiarity with certain interests or a specific field.",
      "- Exceptional writing, research, and communication skills.",
      "- Creativity and adaptability.",
      "- Strong understanding of the target audience and industry trends.",
      "- Proficiency with computers, especially content management software, social media platforms, MS Office, and SEO keywords, basic understanding of HTML",
      "- Ability to sit and type for extended periods.",
      "- Bachelor's Degree in Journalism, English or related field.",
      "- Excellent command of the English language.",
      "- Writing, copy editing, and proofreading experience.",
      "- Good communication and interpersonal skills.",
      "- Highly organized and detail oriented.",
      "- Proficient in desktop publishing software.",
      "- Proficient in Microsoft Office and Social Media platforms.",
      "- High school diploma.",
      "- Bachelor’s degree in marketing, or a related field, preferred.",
      "- Proven working experience as a Promoter.",
      "- Excellent communication, presentation, and leadership skills.",
      "- Proven track record of successful promotions.",
      "- Customer-oriented approach.",
      "- Outgoing and friendly personality.",
      "- Professional appearance.",
      "- Proficient in Microsoft Office Suite.",
      "- Bachelor’s degree in art, graphic design, marketing, communications, journalism and other relevant fields.",
      "- A minimum of 5 years’ digital experience, particularly with, but not limited to web, social and emerging technologies.",
      "- A solid understanding of design, copy and web practices.",
      "- Brilliant interpersonal and communication skills.",
      "- Have an in-depth knowledge of brand development and multichannel marketing models.",
      "- Must be a creative and strategic thinker.",
      "- A degree in writing, communication, language, marketing, or similar.",
      "- Evidence of writing experience (links to published work would be advantageous).",
      "- Critical reading and thinking skills.",
      "- An interest in current events and a general thirst for knowledge.",
      "- Resilience and the ability to accept constructive feedback.",
      "- Basic computer skills.",
      "- A growth mindset.",
      "- High school diploma or GED.",
      "- Previous modeling experience.",
      "- A well-presented portfolio of work.",
      "- A well-maintained physical appearance.",
      "- Willingness to work irregular hours.",
      "- Sound corroborative skills.",
      "- Excellent physical stamina.",
      "- Excellent time management skills.",
      "- Effective communication skills.",
    ],
  },
  {
    "category": "Administration & Office",
    "workPosition": [
      "Administrative officer",
      "Front Desk Clerk",
      "Client Services Coordinator",
      "Librarian",
      "Office Assistant",
      "File Clerk",
      "Tax Associate",
      "Treasurer",
      "Treasury Assistant",
      "Staff Accountant",
      "External Auditor",
      "Comptroller",
      "Billing Clerk",
      "Entry Level Accountant",
      "Budget Analyst",
      "Billing Coordinator",
      "Auditor",
      "External Auditor",
      "Audit Manager",
      "Internal Auditor",
    ],
    "responsibilities": [
      "- Welcome clients and offer them refreshments.",
      "- Transcribe, record, fax and file documents.",
      "- Maintain filing, database systems, and inventories.",
      "- Operate office equipment such as photocopiers and fax machines.",
      "- Communicate with clients and employees, and respond to any queries or complaints.",
      "- Sort and forward incoming mail and emails, and prepare and send outgoing mail.",
      "- Book and prepare meeting rooms and ensure that refreshments are made available.",
      "- Book flights and accommodation as required.",
      "- Coordinate activities and disseminate information to office staff.",
      "- Greet guests and provide them with superb customer service.",
      "- Ensure the front desk is neat, presentable, and equipped with all the necessary supplies such as pens, forms, and paper.",
      "- Answer all client questions and incoming calls.",
      "- Redirect phone calls to the appropriate department and take down messages.",
      "- Accept all letters and packages, and distribute them to their appropriate departments.",
      "- Monitor, organize and forward emails.",
      "- Track and order office equipment and supplies.",
      "- Maintain records and files.",
      "- Oversee the office budget.",
      "- Record, edit and distribute minutes of council meetings.",
      "- Communicate effectively with management, government officials and staff.",
      "- Act as a liaison between the City Council and the public.",
      "- Draft meeting agendas and bylaws.",
      "- Record data and ensure that documents are stored, filed and maintained correctly.",
      "- Utilize computer databases and software.",
      "- Prepare and maintain official reports, legal documents, financial records, and reference material.",
      "- Coordinate municipal elections.",
      "- Transcribe, type and proofread documents.",
      "- Distribute public correspondence and ensure that municipal records are accessible to the public.",
      "- Identify and assess areas of significant business risk.",
      "- Implement best audit and business practices in line with applicable internal audit statements.",
      "- Manage resources and audit assignments.",
      "- Identify and reduce all business and financial risks through effective implementation and monitoring of controls.",
      "- Develop, implement and maintain internal audit policies and procedures in accordance with local and international best practice.",
      "- Compile and implement the annual Internal Audit plan.",
      "- Conduct ad hoc investigations into identified or reported risks.",
      "- Oversee risk-based audits covering operational and financial processes.",
      "- Ensure complete, accurate and timely audit information is reported to Management and/or Risk Committees.",
      "- Overall supervision of planned annual audits.",
      "- Developing and forecasting budgets under direction of CFO.",
      "- Implementing finance and accounting policies and procedures.",
      "- Determining effect of potential business decisions on financial policy.",
      "- Collaborating as company representative with business partners.",
      "- Cooperating with business units and support functions across company.",
      "- Ensuring prompt and accurate month-end and year-end close processes.",
      "- Preparing timely financial statements.",
      "- Reporting variances.",
      "- Overseeing accounting operations such as accounts payable, accounts receivable and general ledger entries.",
      "- Ensuring compliance with company and statutory requirements.",
      "- Maintaining records of assets and liabilities.",
      "- Updating accounts payable.",
      "- Assisting in balancing sheets and income statements.",
      "- Assisting with reviewing income and expenses.",
      "- Preparing regular reports.",
      "- Assisting with other accounting related duties.",
    ],
    "requirements": [
      "- High school diploma or relevant qualification.",
      "- A minimum of 2 years’ proven experience in a similar role.",
      "- Good understanding of office administration and basic bookkeeping practices.",
      "- Superb written and verbal communication skills.",
      "- Excellent organizational and multi-tasking abilities.",
      "- Strong knowledge of MS Office programs.",
      "- High School diploma with relevant experience.",
      "- Certificate in Office Administration or Associate's Degree in Office Management may be required.",
      "- Strong Computer skills and working knowledge of Microsoft Office.",
      "- Time management and organizational skills.",
      "- Attention to detail.",
      "- Personable demeanor.",
      "- Ability to type 45 - 60 WPM (words per minute).",
      "- Bachelor's Degree in Business Administration, Public Administration or related field.",
      "- Previous experience preferred.",
      "- Computer skills and knowledge of software applications.",
      "- Excellent verbal and written communication skills.",
      "- Strong interpersonal skills.",
      "- Time management and organizational skills.",
      "- Compliance with all federal, state and local laws and regulations.",
      "- Degree in Internal Auditing, Financial Accounting or Financial Management (essential).",
      "- Two years of work experience in an internal audit environment.",
      "- Two years of Fraud Auditing experience.",
      "- Accreditation with the Institute of Internal Auditors.",
      "- Exceptional accounting skills.",
      "- Analytical thinker with strong conceptual and problem-solving skills.",
      "- Meticulous attention to detail with the ability to multi-task.",
      "- Ability to work under pressure and meet deadlines.",
      "- Ability to work independently and as part of a team.",
      "- Excellent documentation, communication and IT skills.",
      "- Bachelor's degree in accounting, business or finance.",
      "- 5+ years related work experience.",
      "- Proficient with QuickBooks and Salesforce.",
      "- Proficient with Microsoft Office Word, Excel and Outlook.",
      "- Outstanding knowledge and understanding of applicable laws and regulations.",
      "- Excellent verbal and written communication skills.",
      "- Ability to work as part of a team.",
      "- Ability to provide financial projections.",
      "- High school qualification.",
      "- Good organizational abilities.",
      "- Excellent numerical and analytical skills.",
      "- Knowledge of Accounting and financial reporting competencies.",
      "- Proficiency in MS Office and competency in computer software (e.g. SAP).",
    ]
  },
  {
    "category": "Art, Fashion & Design",
    "workPosition": [
      "Fashion designer",
      "Designer",
      "Dress designer",
      "Interior designer",
      "Furniture designer",
      "Graphic designer",
      "Artist",
      "Painter",
      "Sculptor",
      "Architect",
      "Model",
    ],
    "responsibilities": [
      "- Planning lessons on art and art history in accordance with students' learning objectives.",
      "- Preparing the classroom by gathering and setting up equipment.",
      "- Developing students' drawing, coloring, and painting techniques.",
      "- Providing instruction on the use of media such as graphite and charcoal pencils, as well as oil, acrylic, and watercolor paint.",
      "- Teaching students about art history.",
      "- Assigning and grading projects and examinations.",
      "- Recording and reporting on students' progress.",
      "- Ensuring that the classroom is clean after each lesson.",
      "- Monitoring inventory and sourcing art supplies, as needed.",
      "- Attending faculty and parent-teacher meetings.",
      "- Meeting with clients and determining their needs and requirements.",
      "- Managing design projects from concept development through to completion.",
      "- Developing and presenting project proposals.",
      "- Adjusting designs and plans to meet the client's needs.",
      "- Preparing drawings, blueprints, specifications and construction documents.",
      "- Conducting research and compiling reports on feasibility and environmental impact.",
      "- Complying with safety standards and local planning regulations.",
      "- Determining and adhering to budgets and timelines.",
      "- Managing project teams and collaborating with other construction professionals.",
      "- Meeting with clients to ascertain the intended functions and appearance of each space.",
      "- Anticipating and informing clients of additional features which may be of use to them.",
      "- Giving careful consideration to the placement of water and electrical systems to ensure safety.",
      "- Creating a plan which details the layout and appearance of all installations and loose furniture.",
      "- Suggesting appropriate materials and finishes.",
      "- Assisting clients to select and supervise the work of independent contractors, so that their duties are conducted in accordance with clients' visions.",
      "- Informing clients about appropriate care for their kitchens.",
      "- Keeping a record of hours and activities completed to ensure that clients are billed accurately.",
      "- Observing prescribed building and safety regulations.",
      "- Outline client design objectives.",
      "- Conceptualize and sketch design plans.",
      "- Determine cost of completion and project requirements in the budgeting phase.",
      "- Set a timeline for the completion of an interior design project.",
      "- Source materials and products included in plans.",
      "- Create 'mood boards' to sample your design vision.",
      "- Utilize computer applications in the design process.",
      "- Inspect design after completion to determine whether client goals have been met.",
      "- Following the directions of photographers and posing for photoshoots accordingly.",
      "- Participating in advertisements and television commercials to promote various products and services.",
      "- Participating in runway shows by modeling designers’ clothing, accessories, footwear, and jewelry.",
      "- Participating in trade shows and conventions to advertise business products.",
      "- Maintaining an updated portfolio of work.",
      "- Collaborating with hair and clothing stylists as well as makeup artists to create specific looks.",
      "- Following suitable health and fitness regimens to maintain a well-defined physical appearance in accordance with industry standards.",
      "- Conducting research on designers’ fashionwear as well as other products that are to be modeled and promoted.",
    ],
    "requirements": [
      "- High school diploma or GED.",
      "- Previous modeling experience.",
      "- A well-presented portfolio of work.",
      "- A well-maintained physical appearance.",
      "- Willingness to work irregular hours.",
      "- Sound corroborative skills.",
      "- Excellent physical stamina.",
      "- Excellent time management skills.",
      "- Effective communication skills.",
      "- Bachelor's degree in Fine Arts with teaching qualification, or equivalent.",
      "- Prior experience as an Art Teacher.",
      "- Demonstrated excellence in a variety of art techniques.",
      "- Excellent verbal and written communication skills.",
      "- Capacity to supervise group work.",
      "- Outstanding planning and problem-solving skills.",
      "- Supportive, flexible disposition.",
      "- Available to work during evenings, on occasion.",
      "- Degree in Architecture or a related field.",
      "- Previous experience as an Architect preferred.",
      "- Excellent technical drawing skills.",
      "- Strong communication and project management skills.",
      "- Knowledge of Microsoft Office and software programs such as AutoCAD, Revit, Adobe Creative Suite, Newforma, etc.",
      "- Good interpersonal and presentation skills.",
      "- Knowledge of building codes and regulatory standards.",
      "- Strong creative and visualization skills.",
      "- High school diploma.",
      "- Prior experience as a Kitchen Designer.",
      "- Familiarity with appropriate design and visualization tools.",
      "- Catalog of completed blueprints, plus completed kitchens.",
      "- In-depth knowledge of and strict adherence to the area's building codes.",
      "- Top-notch communication and customer service skills.",
      "- Active listening skills and attention to detail.",
      "- Excellent organizational and time management skills.",
      "- Respect for differing opinions, styles, and financial situations.",
      "- Bachelor's degree in Interior Design or related field.",
      "- Portfolio of design work.",
      "- Project management experience.",
      "- Experience with computational design.",
      "- Highly creative, imaginative and artistic.",
      "- Excellent communication skills, especially in regard to communicating an artistic vision.",
      "- Proficiency in AutoCAD, Illustrator, SketchUp or similar design software.",
    ],
  },
  {
    "category": "Education",
    "workPosition": [
      "Driver Education Teacher",
      "Day Care Assistant",
      "Day Care Center Teacher",
      "Coach",
      "Child Care Assistant",
      "Child Care Center Teacher",
      "Historian",
      "History Teacher",
      "Infant Teacher",
      "Moderator",
      "Nanny",
      "Childcare Teacher",
      "Child Care Provider",
      "Math Teacher",
    ],
    "responsibilities": [
      "- Planning lessons on art and art history in accordance with students' learning objectives.",
      "- Preparing the classroom by gathering and setting up equipment.",
      "- Developing students' drawing, coloring, and painting techniques.",
      "- Providing instruction on the use of media such as graphite and charcoal pencils, as well as oil, acrylic, and watercolor paint.",
      "- Teaching students about art history.",
      "- Assigning and grading projects and examinations.",
      "- Recording and reporting on students' progress.",
      "- Ensuring that the classroom is clean after each lesson.",
      "- Monitoring inventory and sourcing art supplies, as needed.",
      "- Attending faculty and parent-teacher meetings.",
      "- Planning and presenting lessons to facilitate students' understanding and application of mathematical concepts.",
      "- Preparing and distributing learning material such as notes, assignments, and quizzes.",
      "- Sourcing the resources and supplies needed for lessons.",
      "- Ensuring that the classroom remains safe and conducive to learning.",
      "- Grading assignments and quizzes in a timely manner.",
      "- Invigilating quizzes and final examinations.",
      "- Documenting and reporting on students' progress.",
      "- Attending meetings with parents and staff.",
      "- Preparing and presenting lessons that facilitate students' cognitive, social, and emotional development.",
      "- Ensuring that you have sufficient classroom supplies at all times.",
      "- Creating a learning environment that is safe and nurturing.",
      "- Supervising children during lessons, meal time, and on the playground.",
      "- Assisting students to resolve conflict with others.",
      "- Monitoring and notifying caregivers of students' progress.",
      "- Notifying the Department Head and caregivers of accidents or other noteworthy incidents that occur while students are under your supervision.",
      "- Attending meetings with staff and caregivers, as required.",
      "- Accompanying students on field trips, as needed.",
      "- Planning and presenting lessons to facilitate students' understanding and application of mathematical concepts.",
      "- Preparing and distributing learning material such as notes, assignments, and quizzes.",
      "- Sourcing the resources and supplies needed for lessons.",
      "- Ensuring that the classroom remains safe and conducive to learning.",
      "- Grading assignments and quizzes in a timely manner.",
      "- Invigilating quizzes and final examinations.",
      "- Documenting and reporting on students' progress.",
      "- Attending meetings with parents and staff.",
      "- Obtaining historical data from libraries, archives and artifacts.",
      "- Determining the authenticity of historical data.",
      "- Determining the significance of historical data.",
      "- Teaching or researching at universities.",
      "- Translating historical documents into a suitable language.",
      "- Researching the historical development of empires, countries, cities or tribes.",
      "- Preserving artifacts and significant documents in museums or libraries.",
      "- Contributing to academic journals and presenting at conferences.",
      "- Studying history at the intersection of society, culture and economics.",
      "- Assisting and partaking in public exhibits.",
      "- Obtaining extensive information on historical figures for biographies.",
      "- Interviewing subject experts to gain a deeper under understanding of historical events.",
      "- Guiding babies and toddlers through education/development programs.",
      "- Thinking on their feet and responding to each child’s needs efficiently.",
      "- Displaying a patient and calm personality coupled with a loving approach to every child.",
      "- Contributing positively to the behavior and social interaction of the children.",
      "- Building secure relationships with the children.",
      "- Working closely with the principal and department head to ensure that guidelines are adhered to.",
      "- Keeping a diary of the day’s events for parent perusal.",
      "- Reporting accidents, illness, and unusual behavior of children to the principal, head of department, and parents.",
      "- Ensuring close communication with parents throughout the day should the need arise.",
    ],
    "requirements": [
      "- Bachelor’s Degree in Early Childhood Development.",
      "- High School Diploma or Associate Degree (recommended).",
      "- CPR certified and trained.",
      "- Complete Background Check and Health Examination.",
      "- Previous experience in a preschool.",
      "- A passion for working with babies and toddlers.",
      "- Patient, nurturing and thoughtful.",
      "- Good communication skills.",
      "- Maintain discretion around children's records.",
      "- Master's degree in History.",
      "- PhD necessary for research positions.",
      "- Experience in a research position.",
      "- Critical thinking ability and highly analytical mindset.",
      "- Outstanding attention to detail and problem-solving skills.",
      "- Exceptional written and verbal communication.",
      "- Excellent interpersonal skills.",
      "- Good organizational skills.",
      "- Bachelor's degree in Education with a specialization in Mathematics, or equivalent.",
      "- Proven experience as a Math Teacher.",
      "- A thorough understanding of best practices in teaching.",
      "- Excellent verbal and written communication skills.",
      "- Organized, flexible disposition.",
      "- Outstanding interpersonal skills.",
      "- Bachelor's degree in Fine Arts with teaching qualification, or equivalent.",
      "- Prior experience as an Art Teacher.",
      "- Demonstrated excellence in a variety of art techniques.",
      "- Excellent verbal and written communication skills.",
      "- Capacity to supervise group work.",
      "- Outstanding planning and problem-solving skills.",
      "- Supportive, flexible disposition.",
      "- Available to work during evenings, on occasion.",
      "- Bachelor's degree in Education with a specialization in Mathematics, or equivalent.",
      "- Proven experience as a Math Teacher.",
      "- A thorough understanding of best practices in teaching.",
      "- Excellent verbal and written communication skills.",
      "- Organized, flexible disposition.",
      "- Outstanding interpersonal skills.",
      "- Bachelor's degree in Education, preferably with a focus on Early Childhood Development.",
      "- Clear criminal record.",
      "- Proven experience working with young children, ideally in a similar role.",
      "- Physically fit and able to stand for long periods.",
      "- Ability to lift up to 70 pounds independently.",
      "- Valid driver's license with own transport is advantageous.",
      "- Basic first aid training is preferable.",
      "- Excellent organizational and problem-solving skills.",
      "- Energetic, nurturing, and flexible disposition.",
      "- Ability to work during evenings and on weekends, as needed.",
    ],
  },
  {
    "category": "Healthcare",
    "workPosition": [
      "Dermatology Nurse",
      "Dialysis Nurse",
      "Home Health Nurse",
      "Carer",
      "Clinical Liaison",
      "ER Nurse",
      "Chiropractor",
      "Child Psychiatrist",
      "Care Provider",
      "Behavioral Specialist",
      "Dietitian",
      "Family Doctor",
      "Health Coach",
      "Addiction Psychiatrist",
      "Acupuncturist",
      "Certified Diabetes Educator",
    ],
    "responsibilities": [
      "- Being ready to respond and equipped to deal with a medical emergency.",
      "- Quickly assessing patient needs.",
      "- Treating critical injuries, allergic reactions and trauma.",
      "- Performing minor medical operations.",
      "- Cleaning wounds.",
      "- Drawing blood.",
      "- Maintaining emergency room care standards.",
      "- Assisting with insurance paperwork.",
      "- Ensuring the efficiency of the patient check-in process.",
      "- Displaying strong decision-making skills in emergency scenarios.",
      "- Implementing marketing plans to achieve sales goals.",
      "- Cultivating relationships with sources to generate repeat referrals.",
      "- Participating in facility's marketing education, ensuring knowledge of their resources and maintaining knowledge of competitor facilities.",
      "- Providing facility tours and conducting presentations for potential referral sources and patient families.",
      "- Attending seminars and conferences to promote facility.",
      "- Collaborating with facility personnel regarding referrals, evaluations and marketing activities.",
      "- Reviewing physicians' orders and patients' clinical needs, and gathering clinical information.",
      "- Conducting assessments to establish suitability of prospective admissions.",
      "- Communicating activities and concerns to supervisor.",
      "- Completing required paperwork, managing correspondence and maintaining data in CRM.",
      "- Liaising with familial and medical support structures to ascertain residents' care-related requirements.",
      "- Running errands to ensure that the site remains well-stocked.",
      "- Preparing adequate, nutritional meals and assisting with feeding upon request.",
      "- Performing routine, ad hoc household chores.",
      "- Assisting residents to maneuver safely.",
      "- Clearing spaces from potentially hazardous implements.",
      "- Installing assistive devices to prompt self-directed, less restrained functioning.",
      "- Supervising and assisting with treatment adherence.",
      "- Providing unwavering, appropriate emotional support.",
      "- Reviewing maladaptive behaviors to discern potential addictions.",
      "- Formulating sustainable, culturally congruent interventions.",
      "- Administering and perceiving clients' adherence to bespoke treatments.",
      "- Tweaking intervention strategies when deemed suitable.",
      "- Bolstering familial support to solidify treatment gains.",
      "- Curtailing others' enabling behaviors.",
      "- Coordinating inpatient services for highly impaired individuals.",
      "- Develop personal relationships with patients.",
      "- Create patient-specific health programs that make use of historical data.",
      "- Monitor and adapt individualized health programs over time.",
      "- Schedule and administer follow-up examinations.",
      "- Make use of patient health data in medical analyses.",
      "- Offer comprehensive wellness exams.",
      "- Administering vaccinations.",
      "- Perform medical operations.",
      "- Recommending specialists for treatment outside of their capacity.",
      "- Educating patients in health management and disease prevention.",
      "- Offer birthing services.",
      "- Meeting with patients and evaluating their conditions, disorders, or disabilities.",
      "- Diagnosing mental and affective conditions.",
      "- Developing treatment plans, using therapies and counseling, and determining when psychiatric medication is necessary and appropriate.",
      "- Assisting patients as they cope with difficult situations.",
      "- Educating family members or guardians on supporting patients.",
      "- Consulting for social services and court systems.",
      "- Continuing education activities.",
    ],
    "requirements": [
      "- Medical Degree.",
      "- Completion of a three-year family practice residency.",
      "- Training in medical areas such as pediatrics, surgery, neurology, psychiatry, internal medicine, gynecology and community medicine.",
      "- Pass an American Board of Specialties examination to acquire board certification in Family Medicine.",
      "- Excellent written and spoken communication skills.",
      "- Caring, attentive nature.",
      "- Good interpersonal skills.",
      "- Excellent quantitative skills.",
      "- American Heart Association Basic Life Support (BLS) certification.",
      "- Advanced Cardiac Life Support (ACLS) certification.",
      "- Certified Emergency Nurse (CEN) certification and Crisis Prevention and Intervention (CPI) certification advantageous.",
      "- Able to work under high pressure.",
      "- Attention to detail.",
      "- Good organizational skills.",
      "- Excellent written and verbal communication.",
      "- Bachelor’s Degree in nursing or related field.",
      "- 2+ years work experience in healthcare-related marketing.",
      "- Active clinical license.",
      "- Proficient knowledge of Stark laws.",
      "- Proficient computer skills.",
      "- Valid driver’s license with up-to-date insurance.",
      "- Excellent communication skills, using diplomacy and discretion.",
      "- Professional demeanor.",
      "- Excellent organizational skills.",
      "- High school diploma.",
      "- Completion of a Home-Based Caring qualification.",
      "- Demonstrable experience as Carer or similar.",
      "- Driver's license.",
      "- Gentle and clear verbal communication skills.",
      "- Unobtrusive monitoring skills.",
      "- Earnestly compassionate, resourceful, and sensible.",
      "- Physically mobile with good arm strength.",
      "- Possession of a pertinent medical degree.",
      "- Completion of a renowned Psychiatric residency training program.",
      "- Receipt of Addiction Psychiatry training.",
      "- Valid Psychiatric licensure.",
      "- Demonstrable experience as an Addiction Psychiatrist.",
      "- Well-honed diagnostic, psychotherapeutic, and referral techniques.",
      "- Excellent verbal and written communication skills.",
      "- Multiculturally competent.",
      "- A Medical degree in Child Psychiatry and successful completion of residency and fellowship.",
      "- A certification in general psychiatry and licensure in child psychiatry.",
      "- Knowledge of and experience in clinical skills.",
      "- An understanding and empathetic nature.",
      "- Excellent listening and communication skills.",
      "- Ability to work under intense pressure and respond to difficult questions.",
      "- Good note taking and record keeping skills.",
    ],
  },
  {
    "category": "Construction, Installation & Repair",
    "workPosition": [
      "Carpenters",
      "Electricians",
      "Plumbers",
      "Pipefitters",
      "Steamfitters",
      "Mechanics",
      "Installers",
      "Foreman",
      "Lead Carpenter",
      "Framing Carpenter",
      "Roofer",
      "Concrete Foreman",
      "Fence Installer",
      "Construction Worker",
      "Traffic Marshall",
      "Concrete Laborer",
      "Equipment Operator",
      "Building Surveyor"
    ],
    "responsibilities": [
      "- Preparing construction sites, materials, and tools.",
      "- Loading and unloading of materials, tools, and equipment.",
      "- Removing debris, garbage, and dangerous materials from sites.",
      "- Assembling and breaking down barricades, temporary structures, and scaffolding.",
      "- Assisting contractors, e.g. electricians and painters, as required.",
      "- Assisting with transport and operation of heavy machinery and equipment.",
      "- Regulating traffic and erecting traffic signs.",
      "- Following all health and safety regulations.",
      "- Digging holes, tunnels, and shafts.",
      "- Mixing, pouring, and leveling concrete.",
      "- Inspecting the structure of roofs in order to determine the best course of action.",
      "- Providing clients with estimates on labor costs and materials required to fix or build a roof.",
      "- Measuring and cutting materials to ensure that they fit securely around vents, gutters, chimneys, and walls.",
      "- Smoothing out rough spots on roofs to prepare the surface for new shingles or waterproofing.",
      "- Replacing areas of clients’ roofs that are damaged or rotting.",
      "- Installing vapor barriers and insulation to create a more waterproof seal.",
      "- Safely setting up ladders, scaffolding and hoisting equipment as required.",
      "- Updating the supervisor on job progress and reporting any problems related to the job.",
      "- Safely transporting all required equipment and materials to job sites.",
      "- Create and maintain construction schedules.",
      "- Hire and manage staff.",
      "- Liaise with property owners and tenants.",
      "- Order materials as needed.",
      "- Ensure that projects remain within the allotted budget.",
      "- Ensure that safety protocols are followed.",
      "- Inspecting the structure of roofs in order to determine the best course of action.",
      "- Providing clients with estimates on labor costs and materials required to fix or build a roof.",
      "- Measuring and cutting materials to ensure that they fit securely around vents, gutters, chimneys, and walls.",
      "- Smoothing out rough spots on roofs to prepare the surface for new shingles or waterproofing.",
      "- Replacing areas of clients’ roofs that are damaged or rotting.",
      "- Installing vapor barriers and insulation to create a more waterproof seal.",
      "- Safely setting up ladders, scaffolding and hoisting equipment as required.",
      "- Updating the supervisor on job progress and reporting any problems related to the job.",
      "- Safely transporting all required equipment and materials to job sites.",
      "- Assigning and explaining tasks to the project team.",
      "- Communicating with clients in order to determine the time frames within which projects should be completed.",
      "- Calculating the amount of labor, time, and materials needed for each project.",
      "- Creating and adjusting project schedules accordingly.",
      "- Ordering all construction materials needed for projects.",
      "- Supervising the company's field carpenters, unskilled and semi-skilled workers, and subcontractors.",
      "- Performing all carpentry duties required, including both rough and finish carpentry.",
      "- Maintaining accurate records of all work done by the project team.",
      "- Create and maintain construction schedules.",
      "- Hire and manage staff.",
      "- Liaise with property owners and tenants.",
      "- Order materials as needed.",
      "- Ensure that projects remain within the allotted budget.",
      "- Ensure that safety protocols are followed.",
    ],
    "requirements": [
      "- No formal qualification is required, although a high school diploma may be preferred.",
      "- Similar work experience may be beneficial.",
      "- Licensure to work with hazardous materials may be required.",
      "- Willingness to undertake training if necessary.",
      "- Be mild-tempered and a team player.",
      "- Be healthy, strong, and fit.",
      "- High school diploma or GED.",
      "- Valid driver's license.",
      "- State roofer's license.",
      "- Proven roofing or general construction experience.",
      "- Working knowledge of different roofing systems.",
      "- Sound knowledge of business ordinances.",
      "- High school diploma or GED.",
      "- Valid driver's license.",
      "- State roofer's license.",
      "- Proven roofing or general construction experience.",
      "- Working knowledge of different roofing systems.",
      "- Sound knowledge of business ordinances.",
      "- The ability to lift heavy materials and tools.",
      "- The ability to use powered hand tools.",
      "- Excellent communication skills.",
      "- Exceptional customer service skills.",
      "- The ability to lift heavy materials and tools.",
      "- The ability to use powered hand tools.",
      "- Excellent communication skills.",
      "- Exceptional customer service skills.",
      "- Prior experience in a supervisory role.",
      "- Experience with construction.",
      "- Excellent project management skills.",
      "- Good interpersonal skills.",
      "- Excellent leadership skills.",
      "- High school diploma or GED.",
      "- General contractor license.",
      "- Valid driver's license.",
      "- Proven experience in residential remodeling or construction.",
      "- Sound knowledge of safety standards and procedures.",
      "- The ability to safely operate power tools.",
      "- The ability to read blueprints.",
      "- Excellent time management skills.",
      "- Effective communication skills.",
      "- Strong leadership skills.",
      "- Prior experience in a supervisory role.",
      "- Experience with construction.",
      "- Excellent project management skills.",
      "- Good interpersonal skills.",
      "- Excellent leadership skills.",
    ],
  },
  {
    "category": "Restaurant & Hospitality",
    "workPosition": [
      "Waiter",
      "Chef",
      "Baker",
      "Hostess",
      "Kitchen Staff",
      "Food Server",
      "Food Handler",
      "Busboy",
      "Barista",
      "Cook",
      "Dishwasher",
      "Event Planner",
      "Executive Chef",
      "Hotel Manager",
      "Kitchen Porter",
      "Pastry Chef",
      "Kitchen Helper",
    ],
    "responsibilities": [
      "- Cleaning all dishes, work stations, cooking equipment, and food storage areas in accordance with food safety regulations.",
      "- Washing, chopping, shredding, and grating ingredients for subsequent use by the Chef.",
      "- Sweeping and mopping floors, as required.",
      "- Assisting with the unloading of deliveries.",
      "- Storing ingredients according to prescribed food safety regulations.",
      "- Assisting with the monitoring of inventory.",
      "- Reporting all damaged or faulty equipment to the Kitchen Manager.",
      "- Packaging customers' leftover food upon request.",
      "- Cleaning trash cans and disposing refuse on a regular basis.",
      "- Preparing various food items for customers in accordance with the instructions provided.",
      "- Appropriately packaging all food items for delivery.",
      "- Cleaning and disinfecting all food preparation tools, instruments, and equipment before and after each use.",
      "- Ensuring that all food surfaces, as well as refrigerators, ovens, freezers, and microwaves, are clean.",
      "- Promptly notifying the supervisor of any incidents or suspicions of food contamination.",
      "- Cleaning up all spills and leaks as and when they occur to avoid accidents.",
      "- Following proper food storage procedures to prevent spoilage.",
      "- Monitoring food supplies and informing the supervisor of low stock to ensure that the food preparation process isn’t disrupted or delayed due to insufficient ingredients.",
      "- Preparing food rotation labels and labeling all food items accordingly.",
      "- Ensuring that all food is of excellent quality and served in a timely manner.",
      "- Planning the menu, keeping in mind budget and availability of seasonal ingredients.",
      "- Overseeing all kitchen operations.",
      "- Coordinating kitchen staff, and assisting them as required.",
      "- Training staff to prepare and cook all the menu items.",
      "- Taking stock of ingredients and equipment, and placing orders to replenish stock.",
      "- Enforcing safety and sanitation standards in the kitchen.",
      "- Creating new recipes to keep the menu fresh.",
      "- Keeping up to date with industry trends.",
      "- Receiving feedback and making improvements where necessary.",
      "- Identifying clients' requirements and expectations for each event.",
      "- Brainstorming and implementing event concepts and themes.",
      "- Preparing event budgets and processing invoices.",
      "- Researching and booking venues.",
      "- Organizing suppliers, caterers, staff, and entertainment.",
      "- Coordinating all logistical elements of the event.",
      "- Managing set-up, tear-down, and clean-up operations.",
      "- Anticipating attendee needs and making preparations against potential risks.",
      "- Developing post-event reports on the effectiveness of each event.",
      "- Welcoming customers, informing them about specials or new items, answering questions, and accepting orders and payments.",
      "- Preparing foods, such as sandwiches or baked goods, and grinding and blending coffee beans, brewing coffee and tea, and serving items to customers.",
      "- Packaging food and beverages for sale.",
      "- Selling coffee and tea blends and brewing equipment, highlighting the differences between items and educating customers about brewing methods.",
      "- Cleaning and restocking work and dining areas, emptying trash, and sanitizing equipment and utensils.",
      "- Learning about brewing methods, beverage blends, food preparation, and presentation techniques to improve food quality.",
      "- Updating signage and displays to attract customers.",
      "- Taking inventory and replenishing items in display cases, at tables, or behind the counter.",
      "- Working in as part of a fun, high-energy team.",
      "- Adhering to all food safety regulations and quality controls.",
      "- Work with restaurant staff to create a positive dining experience for guests.",
      "- Greet customers and answer questions.",
      "- Alert servers when tables are in need of attention.",
      "- Clean tables and remove dishes after the party leaves.",
      "- Carry loads of soiled dishes to the dishwasher to be cleaned.",
      "- Ensure availability of clean dishes, flatware, glasses, straws, napkins, and other dining materials.",
      "- Washing dishes.",
      "- Be able to remain focused and on-task during busy hours.",
    ],
    "requirements": [
      "- High School Diploma/GED.",
      "- Previous restaurant experience preferred, but not necessary.",
      "- Excellent customer service and communication skills.",
      "- Eye for details.",
      "- Ability to lift 20 lbs or more.",
      "- Willing to stand or walk for extended periods.",
      "- Availability to work evenings and on weekends, including holidays.",
      "- Degree in Hospitality, Public Relations, Management, or related field.",
      "- Experience in project management with a track record of successful events.",
      "- Excellent organizational skills with the ability to multitask under pressure.",
      "- Strong communication and interpersonal skills.",
      "- Creative, out-of-the-box thinking.",
      "- Ability to lead a large team and delegate tasks effectively.",
      "- Meticulous attention to detail.",
      "- Expert time management skills.",
      "- Financial savvy, with the ability to adhere to plan budgets and process invoices.",
      "- High school diploma or equivalent.",
      "- Prior experience in a similar position.",
      "- Thorough knowledge of food safety procedures.",
      "- Excellent organizational, time management, and multitasking abilities.",
      "- Outstanding interpersonal skills.",
      "- Ability to lift up to 50 pounds.",
      "- Capacity to work in a fast-paced environment.",
      "- Ability to stand for extended periods.",
      "- Ability to work shifts, over weekends, and on public holidays, as needed.",
      "- High school diploma or GED.",
      "- A Food Handler's license.",
      "- Proven experience working in the foodservice industry.",
      "- Sound knowledge of food health and safety regulations.",
      "- The ability to follow proper food handling procedures.",
      "- The ability to stand for extended periods.",
      "- The ability to work as part of a team.",
      "- Excellent organizational, time management, and problem-solving skills.",
      "- Effective communication skills.",
      "- Culinary school degree/diploma.",
      "- Past experience as a working chef.",
      "- Advanced knowledge of the culinary arts.",
      "- Perfectionism in sanitation and quality control.",
      "- Portfolio of creative, unique dishes.",
      "- Expert multitasking ability.",
      "- Great leadership and interpersonal skills.",
      "- Ability to run stocktaking and place orders for resupply.",
      "- Exemplary work ethic in a high-pressure environment.",
      "- Passion and pride for delighting people with food.",
      "- High School Diploma or equivalent.",
      "- Experience in food and beverage preparation or customer service preferred.",
      "- Training and willingness to continue learning about food and beverage preparation.",
      "- Exceptional listening and communication skills.",
      "- Ability to walk, bend, and stand for extended periods.",
      "- Availability to work around peak hours, including nights, early mornings, weekends, and holidays.",
      "- A polite, engaging personality.",
      "- Commitment to customer satisfaction and service excellence.",
      "- Willingness to work as part of a high-energy, efficient team in a fast-paced environment.",
    ],
  },
  {
    "category": "Sales & Retail",
    "workPosition": [
      "Cashier",
      "Seller",
      "Merchant",
      "Distributor",
      "Courtesy Clerk",
      "Budtender",
      "Assistant Store Manager",
      "Assistant Buyer",
      "Packaging Designer",
      "Stylist",
      "Stocker",
      "Sales Advisor",
      "Salesperson",
    ],
    "responsibilities": [
      "- Welcoming customers, answering their questions, helping them locate items, and providing advice or recommendations.",
      "- Operating scanners, scales, cash registers, and other electronics.",
      "- Balancing the cash register and generating reports for credit and debit sales.",
      "- Accepting payments, ensuring all prices and quantities are accurate and proving a receipt to every customer.",
      "- Processing refunds and exchanges, resolving complaints.",
      "- Bagging or wrapping purchases to ensure safe transport.",
      "- Following all store procedures regarding coupons, gift cards, or the purchase of specific items, such as alcohol or cigarettes.",
      "- Maintaining a clean workspace.",
      "- Planning and developing merchandising strategies.",
      "- Analyzing sales figures, market trends and customer behavior to determine product needs.",
      "- Stocking sales floor shelves and creating attractive product displays.",
      "- Determining the need for and implementing product promotions, price changes, mark downs, clear outs, etc.",
      "- Ensuring retail staff are well informed on product details and promotions.",
      "- Maintaining and tracking inventory.",
      "- Liaising between customer and company.",
      "- Forecasting sales and profits.",
      "- Managing budgets.",
      "- Research, select and purchase quality products and materials.",
      "- Build relationships with suppliers and negotiate with them for the best pricing.",
      "- Process requisitions and update management on status of orders.",
      "- Update inventory and ensure that stock levels are kept at appropriate levels.",
      "- Arrange transport of goods and track orders to ensure timely delivery.",
      "- Analyze market trends and apply this knowledge to make insightful buying decisions.",
      "- Coordinate with inventory team, management, and stockroom as required.",
      "- Assess quality of stock received and escalate any discrepancies to suppliers and management.",
      "- Ability to travel.",
      "- Advising customers on suitable cannabis products based on their needs, preferences, budgets, and reactions to different strains of cannabis.",
      "- Keeping abreast of new cannabis products on the market as well as the latest industry trends through trade shows and research.",
      "- Processing customers' payments using the dispensary's Point of Sale (POS) system.",
      "- Ensuring that the dispensary is clean and well-organized at all times.",
      "- Educating customers on the safe use of their selected cannabis products.",
      "- Correctly weighing, packaging, and labeling cannabis products as required.",
      "- Checking customers' identification documents to verify that they are of legal age.",
      "- Taking inventory of cannabis products and ensuring that the sales floor is adequately stocked.",
      "- Meeting with the design and marketing teams to discuss packaging specifications and confirm budgets.",
      "- Evaluating market trends and analyzing similar packaging designs.",
      "- Brainstorming packaging ideas using hand sketches, verbal cues, words, and design software.",
      "- Ensuring packaging designs accurately represent the company’s brand and ethos.",
      "- Selecting functional ideas and creating packaging mock-ups.",
      "- Identifying suitable packaging materials and conducting feasibility studies.",
      "- Collaborating with graphic designers and copywriters to finalize packaging text and graphics.",
      "- Completing final mock-up designs using computer modeling software.",
      "- Presenting final designs to stakeholders and company managers.",
      "- Receive goods for the store.",
      "- Pack items.",
      "- Label items with prices.",
      "- Create attractive displays for goods.",
      "- Assist customers with queries.",
    ],
    "requirements": [
      "- High School Diploma or equivalent.",
      "- Customer service or Cashier experience.",
      "- Ability to handle transactions accurately and responsibly.",
      "- High level of energy with strong customer service skills.",
      "- Basic math and computer skills.",
      "- Ability to stand, walk, lift heavy items, and work with other team members in a fast-paced environment to provide excellent service.",
      "- Attention to detail.",
      "- Helpful, courteous approach to resolving complaints.",
      "- High school diploma/GED required.",
      "- Previous experience in merchandising or retail preferred.",
      "- Degree in business, marketing, retail or related field may be preferred.",
      "- Strong organisational and decision making skills.",
      "- Excellent communication skills, both written and verbal.",
      "- Strong numerical and analytical skills.",
      "- Commercial awareness.",
      "- Valid driver's license.",
      "- Bachelor's Degree in relevant field.",
      "- Relevant experience preferred.",
      "- Excellent computer skills (Excel, Microsoft Word, PowerPoint).",
      "- Proficient in appropriate software.",
      "- Critical thinking and negotiation skills.",
      "- Strong communication skills, both written and verbal.",
      "- Occasional domestic and/or international travel.",
      "- High school diploma or GED.",
      "- Proven experience working as a Budtender.",
      "- A valid marijuana worker's permit or license.",
      "- Sound knowledge of cannabis strains and their medicinal benefits.",
      "- Proficiency in all Microsoft Office applications.",
      "- Outstanding organizational skills.",
      "- Excellent analytical and problem-solving skills.",
      "- Effective communication skills.",
      "- Exceptional customer service skills.",
      "- Bachelor’s Degree in Industrial Design, Graphic Design, Art, or a similar field.",
      "- Marketing experience would be preferable.",
      "- Proven experience working as a Packaging Designer.",
      "- Natural talent for design and a keen eye for detail.",
      "- Experience with market research and product placement advertising.",
      "- Familiarity with various packaging materials.",
      "- Knowledge of consumer packaging health and safety regulations.",
      "- Proficient with 3D design software including CAD or AutoCAD.",
      "- Excellent written and verbal communication skills.",
      "- A high school qualification or equivalent.",
      "- Prior experience in retail would be advantageous.",
      "- Professional appearance.",
      "- Friendly disposition.",
      "- Reasonable fitness level.",
    ],
  },
  {
    "category": "Others",
    "workPosition": [
      "Veterinary receptionist",
      "Beekeeper",
      "Dog handler",
      "Dog Trainer",
      "Dog Walker",
      "Florist",
      "Farmer",
      "Pet Groomer",
      "Park Ranger",
      "DevOps Architect",
      "QA Tester",
      "Underwriter",
      "Court Clerk",
    ],
    "responsibilities": [
      "- Conducting environmental site assessments.",
      "- Identifying wetland delineations, and coordinating threatened and endangered species management.",
      "- Conducting habitat evaluations, including presence-absence surveys.",
      "- Collecting specimens.",
      "- Managing storm water run-off, and monitoring erosion control.",
      "- Monitoring construction projects.",
      "- Processing, capturing and analyzing data.",
      "- Compiling technical reports and findings.",
      "- Planning and overseeing field work, and acting as in-field leader for junior staff and technicians.",
      "- Ensuring compliance with safety protocols and procedures.",
      "- Consulting with clients to discuss behavioral concerns and training needs.",
      "- Identifying additional behavioral concerns and communicating them to clients.",
      "- Developing suitable training plans for dogs and documenting their progress.",
      "- Teaching dogs to obey basic commands using various training techniques that are best suited to each dog’s personality and attributes.",
      "- Implementing appropriate training programs to address and resolve problem areas, including aggression, separation anxiety, hyperactivity, and biting.",
      "- Ensuring that the training areas are clean and tidy.",
      "- Teaching clients appropriate training methods to enforce and maintain behaviors and skills learned by their dogs during training sessions.",
      "- Contacting clients to schedule training appointments, verify bookings, and inquire into overdue payments.",
      "- Assembling beehives to desired specifications.",
      "- Inserting honeycombs and inducting wild swarms into prepared hives.",
      "- Forcing bees from a hive using a smoke pot to inspect the hive and retrieve honey.",
      "- Collecting honey and royal jelly.",
      "- Destroying excess queen bee cells to prevent the division of a colony.",
      "- Scraping out hive parasites and removing vermin.",
      "- Destroying diseased bee colonies.",
      "- Cultivating queen bees for sale to other Apiarists.",
      "- Arranging the sale of honey to local buyers.",
      "- Splitting colonies.",
      "- Performing manual labor.",
      "- Performing maintenance on the farm.",
      "- Handling heavy machinery.",
      "- Repairing faulty vehicles and machinery.",
      "- Managing farming activities.",
      "- Overseeing farmworkers.",
      "- Devising strategies for harvesting or breeding.",
      "- Liaising with clients.",
      "- Facilitating the development process and operations.",
      "- Identifying setbacks and shortcomings.",
      "- Creating suitable DevOps channels across the organization.",
      "- Establishing continuous build environments to speed up software development.",
      "- Designing efficient practices.",
      "- Delivering comprehensive best practices.",
      "- Managing and reviewing technical operations.",
      "- Guiding the development team.",
      "- Collect appropriate and accurate information required to assess potential clients and decide on the acceptable risk for a policy.",
      "- Review policy applications based on the previous loss records, age, medical report, credit ratings and driving records.",
      "- Prepare reports that detail risk assessment findings that contribute to the final decision.",
      "- Compare various policies having similar risk undertaking and conduct actuarial studies to decide on the company’s loss records.",
      "- Evaluate policies with regards to the company’s underwriting standards.",
      "- Make a decision to accept, modify or reject an insurance application after scrutiny of all the required documents and studies regarding the risk involved.",
      "- Analyze statistical data using specialized computer programs.",
      "- Write quotes, determine premiums and coverage, and negotiate terms with brokers and clients.",
      "- Carefully select the wording of policies, and prepare the terms and conditions.",
      "- Handle queries from credit control departments, brokers and clients.",
    ],
    "requirements": [
      "- High school diploma or GED.",
      "- Certification through the Certification Council for Professional Dog Trainers (CCPDT) is advantageous.",
      "- Sound knowledge of dog training techniques as well as animal behavior and body language.",
      "- Proven experience working as a Dog Trainer.",
      "- Excellent problem-solving, organizational, and time management skills.",
      "- Strong dog handling skills.",
      "- Effective communication skills.",
      "- A love for dogs.",
      "- Patient and enthusiastic.",
      "- Master’s degree in natural resources, ecology, forestry, environmental science or related field.",
      "- 3+ years work experience in similar role.",
      "- USFSW scientific collection permits.",
      "- Proficient computer skills.",
      "- Proficient with GIS and GPS.",
      "- Knowledge of absence-presence surveys.",
      "- Outstanding communication skills, both verbal and written.",
      "- Ability to work outdoors in unpleasant climatic conditions.",
      "- Valid driver’s license.",
      "- Availability to travel.",
      "- Safety-minded.",
      "- High school diploma or GED.",
      "- Degree in Zoology or Animal Science preferred.",
      "- Proven work experience as a Beekeeper.",
      "- Excellent knowledge of plant and animal biology.",
      "- Ability to remain calm in stressful situations.",
      "- Basic woodworking skills.",
      "- Ability to lift heavy objects.",
      "- Ability to work flexible hours.",
      "- Ability to work unsupervised.",
      "- Ability to work outdoors in all weather conditions.",
      "- Previous experience in the farming industry.",
      "- Knowledge of farming best practices.",
      "- Able to work long hours on location.",
      "- Good communication skills.",
      "- Must be physically fit.",
      "- Excellent hand-eye coordination.",
      "- Degree in Computer Science, Information Systems, or related field.",
      "- Previous experience working on a 24x7 cloud or SaaS operation team.",
      "- Experience with infrastructure management and monitoring.",
      "- Strong knowledge of DevOps Platform tooling ( Chef, Puppet, and Docker.)",
      "- Working knowledge of Automation service provisioning and middleware configuration.",
      "- Ability to work independently and as part of a team.",
      "- Strong analytical skills.",
      "- Degree in Finance or Business Administration (essential).",
      "- Two years of experience as an Underwriter (essential).",
      "- Analytical thinker with research proficiencies.",
      "- Ability to use reasonable and sound judgment.",
      "- Strong problem-solving and decision-making skills.",
      "- Thorough knowledge of databases and tracking systems.",
      "- Solid organizational skills and detail oriented.",
      "- Ability to work under pressure and meet strict deadlines.",
      "- Strong interpersonal and negotiation skills.",
      "- Brilliant IT, math and statistical skills.",
      "- Deep knowledge of underwriting regulations.",
      "- Ability to build positive relationships and partnerships with clients, brokers and key role-players.",
    ],
  },
];
