List<String> categories = [
  "Accounting & Finance",
  "Admin & Office",
  "Advertising & Marketing",
  "Animal Care",
  "Art, Fashion & Design",
  "Business Operations",
  "Cleaning & Facilities",
  "Computer & IT",
  "Construction",
  "Customer Service",
  "Education",
  "Entertainment & Travel",
  "Farming & Outdoors",
  "Healthcare",
  "Human Resources",
  "Installation, Maintenance & Repair",
  "Management",
  "Manufacturing & Warehouse",
  "Media, Communications & Writing",
  "Personal Care & Services",
  "Real Estate",
  "Restaurant & Hospitality",
  "Sales & Retail",
  "Science & Engineering",
  "Social Services & Nonprofit",
  "Sports, Fitness & Recreation",
  "Transportation & Logistics",
  "Others",
];
