import 'dart:math';

class Generator {
  static Map generateAccountData() {
    var emails = [
      "sv883",
      "xmvo4",
      "0aejs",
      "b0w8e",
      "7cvhs",
      "5jsjh",
      "cgwh0",
      "c3qy8",
      "z19d8",
      "4njvl",
      "r5afa",
      "r9twi",
      "r6752",
      "3i7ug",
      "54d9r",
      "o7hdi",
      "0l6ba",
      "y51jh",
      "3jjp5",
      "54js6",
      "4xnfg",
      "ce6jz",
      "kca3g",
      "uo5pt",
      "aujam",
      "nj7gu",
      "u39fh",
      "ekwvl",
      "pxujr",
      "gxsq2",
      "vjnb4",
      "524od",
      "7xo2k",
      "3ct85",
      "5psw1",
      "zno5b",
      "g9dzc",
      "6chkd",
      "m6nsl",
      "vpl9p",
      "o000x",
      "738y1",
      "8le3n",
      "up2f4",
      "22skq",
      "emva4",
      "qoniy",
      "tixcc",
      "8edqx",
      "vs9bf",
      "kfsgz",
      "rmjr6",
      "klv3f",
      "hl4dg",
      "n7ei3",
      "tii10",
      "w3jqj",
      "h1tgi",
      "lucb3",
      "jp7rl",
      "c545f",
      "vmj3m",
      "ausvd",
      "g3nke",
      "7eyd5",
      "jihy5",
      "giyj9",
      "xn3ne",
      "ade1o",
      "r5943",
      "r7v4p",
      "39nc7",
      "z1ryv",
      "qrcoj",
      "023ho",
      "vmjbj",
      "86cmo",
      "z5zrp",
      "st8zg",
      "l9qyf",
      "1rqd8",
      "jhtk9",
      "ojk2e",
      "owm6n",
      "ze675",
      "zkfgc",
      "nh44i",
      "7bj8g",
      "vdgir",
      "wjm8q",
      "ixyve",
      "d6btj",
      "3fvwm",
      "qvxgf",
      "rh13z",
      "nogce",
      "gbs8q",
      "hqkcc",
      "be5b0",
      "zis0b",
    ];

    var random = new Random();
    var name = emails[random.nextInt(emails.length)];
    var num = random.nextInt(100);

    var data = {
      "email": name + num.toString() + "@gmail.com",
      "password": "111111",
      "fullname": name,
      "businessName": name + name,
    };

    return data;
  }
}
